#!/bin/bash
#
# Cubietruck setup script, first part
# Author: @felipeandres254
# Description: Runs automatically on first boot

# Auto-mount disk
uuid=$(blkid | grep /dev/sda1 | cut -d '"' -f 2)
echo -e "UUID=$uuid /mnt/ssd auto nosuid,nodev,nofail 0 0" >> /etc/fstab

# Setup users
useradd cubie
echo -e "root\nroot" | passwd root
echo -e "cubie\ncubie" | passwd cubie
usermod -aG www-data cubie
usermod -aG cubie www-data
usermod -aG sudo cubie
usermod -aG dialout cubie

# Setup network
rm -rf /etc/NetworkManager/system-connections/*
nmcli con add con-name Ethernet \
    type ethernet \
    ifname eth0 \
    ipv4.method manual \
    ipv4.address 192.168.1.101 \
    ipv4.gateway 192.168.1.254 \
    ipv4.dns 8.8.8.8
nmcli device wifi connect "WIFI_SSID" password "WIFI_PASSWORD"
nmcli con mod ISVIMELO \
    ipv4.method manual \
    ipv4.address 192.168.1.100 \
    ipv4.gateway 192.168.1.254 \
    ipv4.dns 8.8.8.8
sleep 300

# Setup boot scripts
cp /mnt/ssd/.cubie/etc/rc.local /etc/rc.local
sed -i "s/^exit 0/# Call init.d scripts/" /etc/rc.local
for file in /mnt/ssd/.cubie/etc/init.d/*; do
    echo "$file &" >> /etc/rc.local
done
echo -e "\nexit 0" >> /etc/rc.local

# Setup crontab
crontab /mnt/ssd/.cubie/home/cubie/.crontab

reboot
