#!/bin/bash
#
# Cubietruck setup script, second part
# Author: @felipeandres254
# Description: Runs automatically on first boot

# Update and upgrade packages
apt-get update
apt-get upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
apt-get install -y dos2unix tree zip zsh python3 python3-pip
pip3 install pyserial
/mnt/ssd/.cubie/home/cubie/install.sh

# Config GIT
git config --global user.name "Andrés Felipe Torres"
git config --global user.email "dev@felipeandres254.io"

# Setup Docker
curl -sSL https://get.docker.com | sh
usermod -aG docker cubie
for file in /mnt/ssd/.cubie/home/cubie/docker/*; do
    filename=$(basename -- $file)
    filename="${filename%.*}"
    docker build -t "cubie/$filename" - < $file
done
