#!/bin/bash
#
# Cubietruck setup script
# Author: @felipeandres254
# Description: Must run after root login, as cubie
#              $ mkdir /hdd; mount /dev/sda1 /hdd; cd /hdd/.cubie; ./setup;

# Auto-mount disk
uuid=$(blkid | grep /dev/sda1 | cut -d '"' -f 2)
echo -e "UUID=$uuid /hdd auto nosuid,nodev,nofail 0 0" >> /etc/fstab

# Setup user
usermod -aG www-data cubie
usermod -aG cubie www-data
for file in home/cubie/.ssh/*; do
    [[ "$file" == "/home/cubie/.ssh/.gitkeep" ]] && continue
    cp $file /$file
done

# Update and upgrade packages
apt-get update
apt-get upgrade -y
apt-get install -y dos2unix tree zip zsh
apt-get install -y apache2 mysql-server php libapache2-mod-php php-mysql
apt-get install -y phpmyadmin php-curl php-mbstring php-gettext
cp ./etc/nanorc /etc/nanorc

# Setup user shell
rm -rf /home/cubie/.oh-my-zsh
./home/cubie/install.sh

# Setup boot scripts
sed -i "s/^exit 0/# Call init.d scripts/" /etc/rc.local
for file in etc/init.d/*; do
    cp $file /$file
    echo "/$file &" >> /etc/rc.local
done
echo -e "\nexit 0" >> /etc/rc.local

reboot
