#!/bin/bash
#
# Cubietruck setup script
# Author: @felipeandres254
# Description: Runs automatically on first boot

# Auto-mount disk
uuid=$(blkid | grep /dev/sda1 | cut -d '"' -f 2)
echo -e "UUID=$uuid /hdd auto nosuid,nodev,nofail 0 0" >> /etc/fstab

# Setup user
useradd cubie
echo -e "cubie\ncubie" | passwd cubie
usermod -aG www-data cubie
usermod -aG cubie www-data
usermod -aG sudo cubie

# Setup network
rm -rf /etc/NetworkManager/system-connections/*
nmcli con add con-name Ethernet \
    type ethernet \
    ifname eth0 \
    ipv4.method manual \
    ipv4.address 192.168.1.101 \
    ipv4.gateway 192.168.1.254 \
    ipv4.dns 8.8.8.8
nmcli device wifi connect "WIFI_SSID" password "WIFI_PASSWORD"
nmcli con mod WIFI_SSID \
    ipv4.method manual \
    ipv4.address 192.168.1.100 \
    ipv4.gateway 192.168.1.254 \
    ipv4.dns 8.8.8.8

# Update and upgrade packages
apt-get update
apt-get upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
apt-get install -y dos2unix tree zip zsh

# Setup Docker
curl -sSL https://get.docker.com | sh
usermod -aG docker cubie
for file in /hdd/.cubie/home/cubie/.docker/*; do
    filename=$(basename -- $file)
    filename="${filename%.*}"
    docker build -t "cubie/$filename" - < $file
done

# Setup boot scripts
cp /hdd/.cubie/etc/rc.local /etc/rc.local
sed -i "s/^exit 0/# Call init.d scripts/" /etc/rc.local
for file in /hdd/.cubie/etc/init.d/*; do
    echo "$file &" >> /etc/rc.local
done
echo -e "\nexit 0" >> /etc/rc.local

# Setup crontab
crontab /hdd/.cubie/.crontab

reboot
