#!/bin/bash

# Show network status via onboard LEDs
for led in /sys/class/leds/*; do
    echo none > $led/trigger
    echo 0 > $led/brightness
done

echo 1 > /sys/class/leds/cubietruck:blue:usr/brightness

sleep 1
while true; do
    curl -sI https://felipeandres254.io >/dev/null
    if [ $? -eq 0 ]; then
        break
    fi
done

sleep .1; echo 1 > /sys/class/leds/cubietruck:orange:usr/brightness;
sleep .1; echo 1 > /sys/class/leds/cubietruck:white:usr/brightness;
sleep .1; echo 1 > /sys/class/leds/cubietruck:green:usr/brightness;

sleep 5;
for led in /sys/class/leds/*; do
    echo none > $led/trigger
    echo 0 > $led/brightness
done
