#!/bin/bash

# Show network status via onboard LEDs
DIR=/sys/class/leds
for led in $DIR/*; do
    echo none > $led/trigger
    echo 0 > $led/brightness
done

echo 1 > $DIR/cubietruck:blue:usr/brightness

sleep 1
while true; do
    curl -sI https://felipeandres254.io >/dev/null
    if [ $? -eq 0 ]; then
        break
    fi
done

sleep .1; echo 1 > $DIR/cubietruck:orange:usr/brightness;
sleep .1; echo 1 > $DIR/cubietruck:white:usr/brightness;
sleep .1; echo 1 > $DIR/cubietruck:green:usr/brightness;

sleep 5;
for led in $DIR/*; do
    echo none > $led/trigger
    echo 0 > $led/brightness
done

sleep 1;
echo heartbeat > $DIR/cubietruck:blue:usr/trigger
echo cpu0 > $DIR/cubietruck:orange:usr/trigger
echo cpu1 > $DIR/cubietruck:white:usr/trigger
echo disk-activity > $DIR/cubietruck:green:usr/trigger
